---
title: "Report"
output: html_document
---

## P8105 Final Group Project 

### Group members (names and UNIS)
-Yang Gao (yg2762) Jiacheng Wu (jw4183) Wentong Liu (wl2829) Yueran Zhang (yz4188) Yuxuan Li (yl4928)

### Project Title
-Park Events In NYC   

### Motivation
-A myriad of park events take place in NYC every year, so it is challenging to collect specific information about events in the parks. Based on data provided by the Department of Parks and Recreation (DPR), we focus our project on the distribution of parks events in NYC with the objectives of classifying parks events with variables of different locations, times, top-rated events, events organizers, as well as events categories. We would like to create a visualized web-based overview of parks events in NYC.  

### Related works
-We were inspired by the Restaurants in NYC that we talked about in the class, as well as the previous works of Risky Coffee. So we were interested in NYC Parks Events. 

### Questions: 
1.Were there any differences in events' time durations between different parks/locations? 

2.What were the most popular times for park events in a day, and how did this change throughout the years?

3.What were the most frequently held events and where were these events located?

4.Which event organizers held the most events?

5.Which borough had the most "must_see" events?

### Data Collection
-Our data was collected by the Department of Parks and Recreation (DPR). There are 7 related tables that make up the NYC Parks Events database, and we used three of those related tables to join on the primary table of events listing. 

-For this project, we used:

1.[Events_Events table](https://data.cityofnewyork.us/City-Government/NYC-Parks-Events-Listing-Event-Locations/cpcm-i88g) (This is the primary table that contains basic data about every event. Each record is an event.)

2.[Events_Categories](https://data.cityofnewyork.us/City-Government/NYC-Parks-Events-Listing-Event-Categories/xtsw-fqvh) (Each record is a category describing an event. One event can be in more than one category.)

3.[Events_Locations](https://data.cityofnewyork.us/City-Government/NYC-Parks-Events-Listing-Event-Locations/cpcm-i88g) (Each record is a location where an event takes place. One event can have more than one location.)

4.[Events_Organizers](https://data.cityofnewyork.us/City-Government/NYC-Parks-Events-Listing-Event-Organizers/jk6k-yab4) (Each record contains a group or person organizing an event. One event can have more than one organizer.)

### Note*
-After meeting with TA, we decided to change our dataset from Restaurants in NYC to Parks Events in NYC. 

-Each member in our group contributed equally to the project. We met frequently both in person and zoom. We divided projects into several parts and we did data processing/analysis, wrote codes/descriptions together. Wentong Liu (wl2829) is responsible for summarizing and committing/pushing everything at the end.

### Discussion: 

  Our project collected data of park events in NYC by mainly focusing on specific locations, boroughs, time, organizers, and categories. We were interested in research questions regarding the number of events each year, the most popular categories, the most popular categories by year and locations, most popular events by organizers, the distribution of NYC parks events by boroughs, the most popular times for park events in a day, as well as the most must-see events and the proportion of free events between different boroughs. 
  
  By data analysis and visualizations, answers to our research questions could be easily observed. We found that the events category of Best for kids was the most popular in NYC, Manhattan had the most events, and the Morning Fitness at Fort Tryon Park in Manhattan was the most popular park event. Manhattan, Brooklyn, and Staten Island are the top three boroughs that held the most free events. We also noticed that 2013 held the most events, and 9:00 am, 10:00 am, and 11:00 am are the top three events’ start-time from 7:00 am to 8:30 pm within a day. 
  
  The results of our project are consistent with our motivation and aim of classifying parks events with variables of different locations, times, top-rated events, events organizers, as well as events categories, which are also helpful for visualizing the distribution of parks events in NYC.